new/mysite/food/urls.py
from django.urls import path
from . import views
app_name="food"
urlpatterns=[
    #food/
    path("",views.index,name="index"),
    #food/item 
    path("item/",views.item,name="item"),
    #food/1
    path("<int:itemid>/",views.details,name="details"),
    #add Item
    path("add/",views.create_item,name="create_item"),
    #update
    path("update/<int:id>",views.update_item,name="update_item"),
    #delete 
    path("delete/<int:id>",views.Delete_item,name="Delete_item"),
]

new/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("food/", include("food.urls")),
    path("register/", user_views.register, name="register"),
    path("login/", authentication_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", authentication_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path("profile/", user_views.profilepage, name="profile"),
] 

# Adding static media URL configuration
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new/mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profile_pictures/user.png',upload_to="profile_pictures")
    location=models.CharField(max_length=100)

    def __str__(self):
        return self.user.username  
     

new/mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['itemname', 'itemdesc', 'itemprice', 'itemimage']

new/mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class meta:
        model= User
        fields= ['username','email','password1','password2']

new/mysite/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm

# Create your views here.
def index(request):
    itemlist=Item.objects.all()
    #template = loader.get_template('food/index.html')
    context={
        "itemlist":itemlist,
    }
    return render(request,'food/index.html',context)

def item(request):
    return HttpResponse("<h1>this is item page...</h1>")

def details(request,itemid):
    item01 = Item.objects.get(pk=itemid)
    context={ 
        'item01':item01,
    }
    return render(request,'food/details.html',context)
def create_item(request):
    form= ItemForm(request.POST or None)     
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form}) 

def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form,'item':item})

def Delete_item(request,id):
    item=Item.objects.get(id=id)

    if request.method =='POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})

new/mysite/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.

def register(request):
    if request.method == 'POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f"Welcome {username},your account is created.")
            return redirect('login') 
    else:
        form = RegisterForm()
    return render (request,'users/register.html',{'form':form})
@login_required
def profilepage(request):
    return render(request,'users/profile.html')

new/mysite/food/templates/food/base.html
    {% load static %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'food/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <title>Document</title>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <a href="#" class="navbar-brand">Food App</a>
            <div class="navbar">
                <a class="nav-item" href="{% url 'food:create_item' %}">Add Menu</a> 
                <a class="nav-item" href="#">View Menu</a>
                <a class="nav-item" href="#">Delete Menu</a>
                {% if user.is_authenticated %}
                    <a class="nav-item" href="{% url 'logout' %}">logout</a>
                    <a class="nav-item" href="{% url 'profile' %}">Profile</a>
                {% else %}
                    <a class="nav-item" href="{% url 'login' %}">login</a> 
                {% endif %}
            </div>
        </nav>
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% block body %}
        {% endblock %}
    </body>
    </html>

new/mysite/food/templates/food/details.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="150px"  src="{{item01.itemimage}}" class="card"/>
        </div>
        <div class="col-md-6">
            <h1>{{ item01.itemname}}</h1>
            <h1>{{ item01.itemdesc}}</h1>
            <h1>Rs{{ item01.itemprice}}</h1>
            <a href="{% url 'food:Delete_item' item01.id %}">Delete</a>           
        </div>
    </div>
</div>
{% endblock %}  

new/mysite/food/templates/food/index.html
    {% extends 'food/base.html' %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    <body>  
        {%block body %}
        {% for item in itemlist %}
            <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img class="card" height="150px" src="{{item.itemimage}}"/>
                </div>
                <div class="col-md-4">
                    <h3>{{ item.itemname}}</h3>
                    <h5>{{ item.itemdesc}}</h5>
                    <h6>Rs{{item.itemprice}}</h6>    
                </div>
                <div class="col-md-2">
                    <a href="{% url 'food:details' item.id %}" class="btn btn-success">details</a>
                </div>
                    
            </div>
        
        {% endfor %}
        {% endblock %}

                <ul>    
                    <li>
                        <a href=""> {{item.id }} -- {{ item.itemname }}</a>
                    </li>
                </ul>
            
    </body>
    </html>

new/mysite/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h1>Are you sure you want to delete this {{ item.name }}</h1>
    <button type="submit">Confirm</button>
</form>

new/mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}